### ISSUE TITLE
Bug: After downloading and running the program on en to bn package created but not loadable by anki.

### ISSUE THREAD

**Issue by robotcorner** [abdnh/50langs2anki#2]
Hello, 

As the title states after running the program the package is made, however I have not been able to import the package with QT5, or QT6 version of anki. I'm not sure what's wrong as no error messages pop up. 

![image](https://user-images.githubusercontent.com/20550117/221487616-e54f3a20-3fcb-40df-8b19-00886f4a9ccb.png)

**Comment by abdnh** [comment]
50languages.com was redesigned recently and this broke the script. Will look into fixing it.

**Comment by abdnh** [comment]
I pushed a fix. Let me know if it doesn't work for you.
